### ISSUE TITLE
运行python test.py --benchmark FashionMNIST 报错

### ISSUE THREAD

**Issue by lemon356** [GTMLLab/VeryFL#4]
(py39) PS E:\PyCharm 2023.2.2\FL\VeryFL> python test.py --benchmark FashionMNIST 
信息: 用提供的模式无法找到文件。

Launching 'ganache-cli.cmd --chain.vmErrorsOnRPCResponse true --server.port 8545 --miner.blockGasLimit 12000000 --wallet.totalAccounts 10 --hardfork istanbul --wallet.mnemonic brownie'
...
Transaction sent: 0x54ee31527d50e0e75bb4f24e86eb472375b57d634f4c55660c57995b89c45e88
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 0
  watermarkNegotiation.constructor confirmed   Block: 1   Gas used: 188001 (1.57%)
  watermarkNegotiation deployed at: 0x3194cBDC3dbcd3E11a07892e7bA5c3394048Cc87

Transaction sent: 0xbe7689f8845f21285fb71b825b9ad425a61d55ea0b2879a0b636cd89a1ba5f03
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 1
  clientManager.constructor confirmed   Block: 2   Gas used: 194011 (1.62%)
  clientManager deployed at: 0x602C71e4DAC47a042Ee7f46E0aee17F94A3bA0B6

mnemonic: 'thrive crush check proof wrist jelly machine relief neglect address suggest fantasy'
信息: 用提供的模式无法找到文件。
信息: 用提供的模式无法找到文件。
信息: 用提供的模式无法找到文件。
信息: 用提供的模式无法找到文件。
E:\anaconda3\envs\py39\lib\site-packages\brownie\network\main.py:44: BrownieEnvironmentWarning: Development network has a block height of 2
  warnings.warn(
E:\anaconda3\envs\py39\lib\site-packages\brownie\network\main.py:44: BrownieEnvironmentWarning: Development network has a block height of 2
  warnings.warn(
E:\anaconda3\envs\py39\lib\site-packages\brownie\network\main.py:44: BrownieEnvironmentWarning: Development network has a block height of 2
  warnings.warn(
E:\anaconda3\envs\py39\lib\site-packages\brownie\network\main.py:44: BrownieEnvironmentWarning: Development network has a block height of 2
  warnings.warn(
Attached to local RPC client listening at '127.0.0.1:8545'...
Attached to local RPC client listening at '127.0.0.1:8545'...
Attached to local RPC client listening at '127.0.0.1:8545'...
Attached to local RPC client listening at '127.0.0.1:8545'...
Transaction sent: 0x6e647795133346638efbaa26f5e645c1968d52c60b50b78bd8121c78faea3358
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 2
  watermarkNegotiation.constructor confirmed   Block: 3   Gas used: 188001 (1.57%)
  watermarkNegotiation deployed at: 0xE7eD6747FaC5360f88a2EFC03E00d25789F69291

Transaction sent: 0x34e30e2f61349ffa0a06f4da7ea6cf72a059285e0236a04721e55e16bdbc2679
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\anaconda3\envs\py39\lib\multiprocessing\spawn.py", line 116, in spawn_main
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 3
    exitcode = _main(fd, parent_sentinel)
  File "E:\anaconda3\envs\py39\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "E:\anaconda3\envs\py39\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\anaconda3\envs\py39\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "E:\anaconda3\envs\py39\lib\runpy.py", line 288, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "E:\anaconda3\envs\py39\lib\runpy.py", line 97, in _run_module_code
Traceback (most recent call last):
    _run_code(code, mod_globals, init_globals,
  File "<string>", line 1, in <module>
  File "E:\anaconda3\envs\py39\lib\runpy.py", line 87, in _run_code
  File "E:\anaconda3\envs\py39\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exec(code, run_globals)
  File "E:\PyCharm 2023.2.2\FL\VeryFL\test.py", line 4, in <module>
    exitcode = _main(fd, parent_sentinel)
  File "E:\anaconda3\envs\py39\lib\multiprocessing\spawn.py", line 125, in _main
    from task import Task
  File "E:\PyCharm 2023.2.2\FL\VeryFL\task.py", line 6, in <module>
    prepare(preparation_data)
  File "E:\anaconda3\envs\py39\lib\multiprocessing\spawn.py", line 236, in prepare
    from config.algorithm import Algorithm
  File "E:\PyCharm 2023.2.2\FL\VeryFL\config\algorithm.py", line 2, in <module>
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\anaconda3\envs\py39\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    from server.base.baseAggregator import ServerAggregator
  File "E:\PyCharm 2023.2.2\FL\VeryFL\server\base\baseAggregator.py", line 3, in <module>
    main_content = runpy.run_path(main_path,
  File "E:\anaconda3\envs\py39\lib\runpy.py", line 288, in run_path
    from client.clients import Client
  File "E:\PyCharm 2023.2.2\FL\VeryFL\client\clients.py", line 5, in <module>
    return _run_module_code(code, init_globals, run_name,
  File "E:\anaconda3\envs\py39\lib\runpy.py", line 97, in _run_module_code
    from client.base.baseTrainer import BaseTrainer
  File "E:\PyCharm 2023.2.2\FL\VeryFL\client\base\baseTrainer.py", line 4, in <module>
    _run_code(code, mod_globals, init_globals,
  File "E:\anaconda3\envs\py39\lib\runpy.py", line 87, in _run_code
    from chainfl.interact import chainProxy
  File "E:\PyCharm 2023.2.2\FL\VeryFL\chainfl\interact.py", line 22, in <module>
    exec(code, run_globals)
    watermarkNegotiation.deploy({'from':server_accounts})
  File "E:\PyCharm 2023.2.2\FL\VeryFL\test.py", line 4, in <module>
  File "E:\anaconda3\envs\py39\lib\site-packages\brownie\network\contract.py", line 553, in __call__
    from task import Task
  File "E:\PyCharm 2023.2.2\FL\VeryFL\task.py", line 6, in <module>
    return tx["from"].deploy(
  File "E:\anaconda3\envs\py39\lib\site-packages\brownie\network\account.py", line 526, in deploy
    from config.algorithm import Algorithm
  File "E:\PyCharm 2023.2.2\FL\VeryFL\config\algorithm.py", line 2, in <module>
    receipt, exc = self._make_transaction(
    from server.base.baseAggregator import ServerAggregator
  File "E:\anaconda3\envs\py39\lib\site-packages\brownie\network\account.py", line 773, in _make_transaction
  File "E:\PyCharm 2023.2.2\FL\VeryFL\server\base\baseAggregator.py", line 3, in <module>
    exc = VirtualMachineError(e)
    from client.clients import Client
  File "E:\anaconda3\envs\py39\lib\site-packages\brownie\exceptions.py", line 115, in __init__
  File "E:\PyCharm 2023.2.2\FL\VeryFL\client\clients.py", line 5, in <module>
    raise ValueError(exc["message"]) from None
    from client.base.baseTrainer import BaseTrainer
ValueError: the tx doesn't have the correct nonce. account has nonce of: 4 tx has nonce of: 3
  File "E:\PyCharm 2023.2.2\FL\VeryFL\client\base\baseTrainer.py", line 4, in <module>
    from chainfl.interact import chainProxy
  File "E:\PyCharm 2023.2.2\FL\VeryFL\chainfl\interact.py", line 22, in <module>
    watermarkNegotiation.deploy({'from':server_accounts})
  File "E:\anaconda3\envs\py39\lib\site-packages\brownie\network\contract.py", line 553, in __call__
    return tx["from"].deploy(
  File "E:\anaconda3\envs\py39\lib\site-packages\brownie\network\account.py", line 526, in deploy
    receipt, exc = self._make_transaction(
  File "E:\anaconda3\envs\py39\lib\site-packages\brownie\network\account.py", line 773, in _make_transaction
    exc = VirtualMachineError(e)
  File "E:\anaconda3\envs\py39\lib\site-packages\brownie\exceptions.py", line 115, in __init__
    raise ValueError(exc["message"]) from None
ValueError: the tx doesn't have the correct nonce. account has nonce of: 4 tx has nonce of: 3
Transaction sent: 0xa62e7ea928185004fbf93ed2d24b6e929a2400b1f229889e943157d2c573d35a
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 4
  watermarkNegotiation.constructor confirmed   Block: 4   Gas used: 188001 (1.57%)
  watermarkNegotiation deployed at: 0x6951b5Bd815043E3F842c1b026b0Fa888Cc2DD85

  clientManager.constructor confirmed   Block: 5   Gas used: 194011 (1.62%)
  clientManager deployed at: 0xe0aA552A10d7EC8760Fc6c246D391E698a82dDf9

Transaction sent: 0x4b6e9727b6037ad5db58f0fb35a8a84d3b11d4032f3ef36c9352147e84aab340
  Gas price: 0.0 gwei   Gas limit: 12000000   Nonce: 5
  clientManager.constructor confirmed   Block: 6   Gas used: 194011 (1.62%)
  clientManager deployed at: 0x6b4BDe1086912A6Cb24ce3dB43b3466e6c72AFd3

Traceback (most recent call last):
  File "E:\anaconda3\envs\py39\lib\site-packages\torch\utils\data\dataloader.py", line 1120, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "E:\anaconda3\envs\py39\lib\multiprocessing\queues.py", line 114, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\PyCharm 2023.2.2\FL\VeryFL\test.py", line 24, in <module>
    classification_task.run()
  File "E:\PyCharm 2023.2.2\FL\VeryFL\task.py", line 111, in run
    client.train(epoch = i)
  File "E:\PyCharm 2023.2.2\FL\VeryFL\client\clients.py", line 153, in train
    ret_list = cal.train(self.args.get('num_steps'))
  File "E:\PyCharm 2023.2.2\FL\VeryFL\client\base\baseTrainer.py", line 83, in train
    ret_list.append(self._train_epoch(epoch))
  File "E:\PyCharm 2023.2.2\FL\VeryFL\client\trainer\normalTrainer.py", line 25, in _train_epoch
    for _, (x, labels) in enumerate(self.dataloader):
  File "E:\anaconda3\envs\py39\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__
    data = self._next_data()
  File "E:\anaconda3\envs\py39\lib\site-packages\torch\utils\data\dataloader.py", line 1316, in _next_data
    idx, data = self._get_data()
  File "E:\anaconda3\envs\py39\lib\site-packages\torch\utils\data\dataloader.py", line 1282, in _get_data
    success, data = self._try_get_data()
  File "E:\anaconda3\envs\py39\lib\site-packages\torch\utils\data\dataloader.py", line 1133, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 25632, 29680) exited unexpectedly
Terminating local RPC client...

**Comment by sdlcgzm** [comment]
请问解决了吗，我也遇到了相同的问题

**Comment by lemon356** [comment]
没有，我尝试了不同操作系统，但是遇到了一样的问题

**Comment by lemon356** [comment]
> 请问解决了吗，我也遇到了相同的问题

没有，我尝试了不同操作系统，但是遇到了一样的问题

**Comment by sdlcgzm** [comment]
> > 请问解决了吗，我也遇到了相同的问题
> 
> 没有，我尝试了不同操作系统，但是遇到了一样的问题

好的，谢谢
